# 🧩 Reto 2 – pH
**Objetivo:** clasificar pH y generar alerta química.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `pH`.
3. Crea `clasificacion_pH` con tres rangos.
4. Crea `alerta_quimica` (revisión si pH < 6.5 o pH > 8.5).
5. Filtra `df_alerta` y exporta `resultado_ph.csv`.

> **Reto adicional:** promedio y desviación estándar.

In [1]:
import pandas as pd
import numpy as np

# 1. Cargar el CSV en df
df = pd.read_csv("../data/muestras_calidad_agua.csv")

# Mostrar las primeras filas para verificar los datos
df.head()

                          sitio   pH  oxigeno  temperatura
0                Río Subachoque  7.2      7.8         18.5
1   Quebrada Honda (Facatativá)  6.3      6.2         19.4
2          Río Botello (Madrid)  6.8      5.9         22.7
3  Afluente San José (El Rosal)  7.9      8.3         20.1
4                   Río Villeta  8.7      6.1         28.3

In [2]:
# Limpiar posibles espacios en los nombres de columnas
df.columns = df.columns.str.strip()

# Buscar automáticamente las columnas necesarias
col_sitio = [col for col in df.columns if "sitio" in col.lower()][0]
col_ph = [col for col in df.columns if "ph" in col.lower()][0]

# 2. Extraer sitio y pH en df_ph
df_ph = df[[col_sitio, col_ph]].copy()

# Renombrar columnas para trabajar más fácil
df_ph.columns = ["sitio", "pH"]

df_ph

                           sitio   pH
0                 Río Subachoque  7.2
1    Quebrada Honda (Facatativá)  6.3
2           Río Botello (Madrid)  6.8
3   Afluente San José (El Rosal)  7.9
4                    Río Villeta  8.7
5  Quebrada Cune (San Francisco)  6.0
6            Río Tobia (Nocaima)  7.4
7       Quebrada Negra (La Vega)  7.6
8          Río Bahamón (Sasaima)  8.1
9        Río Guayuriba (La Mesa)  5.9

In [3]:
# 3. Crear clasificacion_pH con tres rangos

df_ph["clasificacion_pH"] = np.where(
    df_ph["pH"] < 6.5,
    "Ácido",
    np.where(
        df_ph["pH"] <= 8.5,
        "Adecuado",
        "Alcalino"
    )
)

df_ph

                           sitio   pH clasificacion_pH
0                 Río Subachoque  7.2         Adecuado
1    Quebrada Honda (Facatativá)  6.3            Ácido
2           Río Botello (Madrid)  6.8         Adecuado
3   Afluente San José (El Rosal)  7.9         Adecuado
4                    Río Villeta  8.7         Alcalino
5  Quebrada Cune (San Francisco)  6.0            Ácido
6            Río Tobia (Nocaima)  7.4         Adecuado
7       Quebrada Negra (La Vega)  7.6         Adecuado
8          Río Bahamón (Sasaima)  8.1         Adecuado
9        Río Guayuriba (La Mesa)  5.9            Ácido

In [4]:
# 4. Crear alerta_quimica

df_ph["alerta_quimica"] = np.where(
    (df_ph["pH"] < 6.5) | (df_ph["pH"] > 8.5),
    "Sí",
    "No"
)

df_ph

                           sitio   pH clasificacion_pH alerta_quimica
0                 Río Subachoque  7.2         Adecuado             No
1    Quebrada Honda (Facatativá)  6.3            Ácido             Sí
2           Río Botello (Madrid)  6.8         Adecuado             No
3   Afluente San José (El Rosal)  7.9         Adecuado             No
4                    Río Villeta  8.7         Alcalino             Sí
5  Quebrada Cune (San Francisco)  6.0            Ácido             Sí
6            Río Tobia (Nocaima)  7.4         Adecuado             No
7       Quebrada Negra (La Vega)  7.6         Adecuado             No
8          Río Bahamón (Sasaima)  8.1         Adecuado             No
9        Río Guayuriba (La Mesa)  5.9            Ácido             Sí

In [5]:
# 5. Filtrar sitios con alerta química

df_alerta = df_ph[df_ph["alerta_quimica"] == "Sí"]

df_alerta

                           sitio   pH clasificacion_pH alerta_quimica
1    Quebrada Honda (Facatativá)  6.3            Ácido             Sí
4                    Río Villeta  8.7         Alcalino             Sí
5  Quebrada Cune (San Francisco)  6.0            Ácido             Sí
9        Río Guayuriba (La Mesa)  5.9            Ácido             Sí

In [6]:
# Exportar resultado a un archivo CSV

df_ph.to_csv("resultado_ph.csv", index=False)

print("Archivo resultado_ph.csv creado correctamente.")

Archivo resultado_ph.csv creado correctamente.

In [7]:
# Reto adicional: promedio y desviación estándar del pH

promedio_ph = df_ph["pH"].mean()
desviacion_ph = df_ph["pH"].std()

print("Promedio de pH:", round(promedio_ph, 2))
print("Desviación estándar del pH:", round(desviacion_ph, 2))

Promedio de pH: 7.19
Desviación estándar del pH: 0.93

## Conclusión

A partir del análisis del pH, se clasificaron los sitios en tres categorías: ácido, adecuado y alcalino.

Los valores de pH menores a 6.5 se consideran ácidos, mientras que los valores mayores a 8.5 se consideran alcalinos. Estos casos generan una alerta química porque están fuera del rango adecuado.

El promedio y la desviación estándar permiten observar el comportamiento general del pH en los sitios analizados.