# 🧩 Reto 1 – Temperatura
**Objetivo:** clasificar la temperatura del agua y evaluar posible estrés térmico.

**Datos:** `../data/muestras_calidad_agua.csv`

### Pasos
1. Carga el CSV en `df`.
2. Extrae `sitio` y `temperatura` en `df_temp`.
3. Crea `categoria_temp` con np.where o .loc.
4. Crea `riesgo_termico`.
5. Filtra a `df_caliente` (alta temperatura).
6. Exporta `resultado_temperatura.csv`.

> **Reto adicional:** porcentaje de sitios con riesgo térmico.

In [3]:
import pandas as pd
import numpy as np

# 1. Cargar el CSV en df
df = pd.read_csv("../data/muestras_calidad_agua.csv")


# Verificar columnas disponibles
df.head()

                          sitio   pH  oxigeno  temperatura
0                Río Subachoque  7.2      7.8         18.5
1   Quebrada Honda (Facatativá)  6.3      6.2         19.4
2          Río Botello (Madrid)  6.8      5.9         22.7
3  Afluente San José (El Rosal)  7.9      8.3         20.1
4                   Río Villeta  8.7      6.1         28.3

In [4]:
# Limpiar posibles espacios en los nombres de columnas
df.columns = df.columns.str.strip()

# Buscar automáticamente las columnas necesarias
col_sitio = [col for col in df.columns if "sitio" in col.lower()][0]
col_temperatura = [col for col in df.columns if "temperatura" in col.lower()][0]

# 2. Extraer sitio y temperatura en df_temp
df_temp = df[[col_sitio, col_temperatura]].copy()

# Renombrar columnas para trabajar más fácil
df_temp.columns = ["sitio", "temperatura"]

df_temp

                           sitio  temperatura
0                 Río Subachoque         18.5
1    Quebrada Honda (Facatativá)         19.4
2           Río Botello (Madrid)         22.7
3   Afluente San José (El Rosal)         20.1
4                    Río Villeta         28.3
5  Quebrada Cune (San Francisco)         25.2
6            Río Tobia (Nocaima)         26.9
7       Quebrada Negra (La Vega)         24.4
8          Río Bahamón (Sasaima)         27.6
9        Río Guayuriba (La Mesa)         30.5

In [5]:
# 3. Crear categoria_temp usando np.where

df_temp["categoria_temp"] = np.where(
    df_temp["temperatura"] <= 20,
    "Baja",
    np.where(
        df_temp["temperatura"] <= 26,
        "Media",
        "Alta"
    )
)

df_temp

                           sitio  temperatura categoria_temp
0                 Río Subachoque         18.5           Baja
1    Quebrada Honda (Facatativá)         19.4           Baja
2           Río Botello (Madrid)         22.7          Media
3   Afluente San José (El Rosal)         20.1          Media
4                    Río Villeta         28.3           Alta
5  Quebrada Cune (San Francisco)         25.2          Media
6            Río Tobia (Nocaima)         26.9           Alta
7       Quebrada Negra (La Vega)         24.4          Media
8          Río Bahamón (Sasaima)         27.6           Alta
9        Río Guayuriba (La Mesa)         30.5           Alta

In [6]:
# 4. Crear riesgo_termico usando np.where

df_temp["riesgo_termico"] = np.where(
    df_temp["temperatura"] > 26,
    "Sí",
    "No"
)

df_temp

                           sitio  temperatura categoria_temp riesgo_termico
0                 Río Subachoque         18.5           Baja             No
1    Quebrada Honda (Facatativá)         19.4           Baja             No
2           Río Botello (Madrid)         22.7          Media             No
3   Afluente San José (El Rosal)         20.1          Media             No
4                    Río Villeta         28.3           Alta             Sí
5  Quebrada Cune (San Francisco)         25.2          Media             No
6            Río Tobia (Nocaima)         26.9           Alta             Sí
7       Quebrada Negra (La Vega)         24.4          Media             No
8          Río Bahamón (Sasaima)         27.6           Alta             Sí
9        Río Guayuriba (La Mesa)         30.5           Alta             Sí

In [7]:
# 5. Filtrar sitios con alta temperatura

df_caliente = df_temp[df_temp["categoria_temp"] == "Alta"]

df_caliente

                     sitio  temperatura categoria_temp riesgo_termico
4              Río Villeta         28.3           Alta             Sí
6      Río Tobia (Nocaima)         26.9           Alta             Sí
8    Río Bahamón (Sasaima)         27.6           Alta             Sí
9  Río Guayuriba (La Mesa)         30.5           Alta             Sí

In [8]:
# 6. Exportar resultado a un archivo CSV

df_temp.to_csv("resultado_temperatura.csv", index=False)

print("Archivo resultado_temperatura.csv creado correctamente.")

Archivo resultado_temperatura.csv creado correctamente.

In [10]:
# Reto adicional: porcentaje de sitios con riesgo térmico

total_sitios = len(df_temp)
sitios_con_riesgo = len(df_temp[df_temp["riesgo_termico"] == "Sí"])

porcentaje_riesgo = (sitios_con_riesgo / total_sitios) * 100

print("Total de sitios:", total_sitios)
print("Sitios con riesgo térmico:", sitios_con_riesgo)
print("Porcentaje de sitios con riesgo térmico:", round(porcentaje_riesgo, 2), "%")

Total de sitios: 10
Sitios con riesgo térmico: 4
Porcentaje de sitios con riesgo térmico: 40.0 %

## Conclusión

A partir del análisis de la temperatura, se clasificaron los sitios en temperatura baja, media y alta.

Los sitios con temperatura alta se consideran con posible riesgo térmico, ya que las temperaturas elevadas pueden reducir la cantidad de oxígeno disponible en el agua y afectar la vida acuática.

El porcentaje calculado permite identificar qué proporción de los sitios evaluados presenta riesgo térmico.