# 🧩 Reto 4 – Integración de resultados
**Objetivo:** combinar resultados parciales en un diagnóstico integral por sitio.

### Pasos
1. Carga `resultado_temperatura.csv`, `resultado_ph.csv`, `resultado_oxigeno.csv`.
2. Únelos por `sitio` usando `merge`.
3. Crea `diagnostico_final` con reglas (parcial/total/normal).
4. Exporta `diagnostico_final.csv`.
5. Cuenta categorías con `value_counts()`.

> **Reto adicional:** gráfico de barras de distribución.

In [1]:
import os

os.listdir()

['.ipynb_checkpoints',
 '0_ejemplo_clase_condicionales.ipynb',
 'resultado_ph.csv',
 'resultado_temperatura.csv',
 'reto1_temperatura.ipynb',
 'reto2_ph.ipynb',
 'reto3_oxigeno.ipynb',
 'reto4_integracion.ipynb']

In [2]:
os.listdir("../notebooks")

['.ipynb_checkpoints',
 '0_ejemplo_clase_condicionales.ipynb',
 'resultado_ph.csv',
 'resultado_temperatura.csv',
 'reto1_temperatura.ipynb',
 'reto2_ph.ipynb',
 'reto3_oxigeno.ipynb',
 'reto4_integracion.ipynb']

In [3]:
import pandas as pd

temp = pd.read_csv("resultado_temperatura.csv")
ph = pd.read_csv("resultado_ph.csv")

In [4]:
temp.head()

                          sitio  temperatura categoria_temp riesgo_termico
0                Río Subachoque         18.5           Baja             No
1   Quebrada Honda (Facatativá)         19.4           Baja             No
2          Río Botello (Madrid)         22.7          Media             No
3  Afluente San José (El Rosal)         20.1          Media             No
4                   Río Villeta         28.3           Alta             Sí

In [5]:
ph.head()

                          sitio   pH clasificacion_pH alerta_quimica
0                Río Subachoque  7.2         Adecuado             No
1   Quebrada Honda (Facatativá)  6.3            Ácido             Sí
2          Río Botello (Madrid)  6.8         Adecuado             No
3  Afluente San José (El Rosal)  7.9         Adecuado             No
4                   Río Villeta  8.7         Alcalino             Sí

In [6]:
df_final = pd.concat([temp, ph], ignore_index=True)

df_final

,sitio,temperatura,categoria_temp,riesgo_termico,pH,clasificacion_pH,alerta_quimica
0,Río Subachoque,18.5,Baja,No,NaN,NaN,NaN
1,Quebrada Honda (Facatativá),19.4,Baja,No,NaN,NaN,NaN
2,Río Botello (Madrid),22.7,Media,No,NaN,NaN,NaN
3,Afluente San José (El Rosal),20.1,Media,No,NaN,NaN,NaN
4,Río Villeta,28.3,Alta,Sí,NaN,NaN,NaN
5,Quebrada Cune (San Francisco),25.2,Media,No,NaN,NaN,NaN
6,Río Tobia (Nocaima),26.9,Alta,Sí,NaN,NaN,NaN
7,Quebrada Negra (La Vega),24.4,Media,No,NaN,NaN,NaN
8,Río Bahamón (Sasaima),27.6,Alta,Sí,NaN,NaN,NaN
9,Río Guayuriba (La Mesa),30.5,Alta,Sí,NaN,NaN,NaN
10,Río Subachoque,NaN,NaN,NaN,7.2,Adecuado,No
11,Quebrada Honda (Facatativá),NaN,NaN,NaN,6.3,Ácido,Sí
12,Río Botello (Madrid),NaN,NaN,NaN,6.8,Adecuado,No
13,Afluente San José (El Rosal),NaN,NaN,NaN,7.9,Adecuado,No
14,Río Villeta,NaN,NaN,NaN,8.7,Alcalino,Sí
15,Quebrada Cune (San Francisco),NaN,NaN,NaN,6.0,Ácido,Sí
16,Río Tobia (Nocaima),NaN,NaN,NaN,7.4,Adecuado,No
17,Quebrada Negra (La Vega),NaN,NaN,NaN,7.6,Adecuado,No
18,Río Bahamón (Sasaima),NaN,NaN,NaN,8.1,Adecuado,No
19,Río Guayuriba (La Mesa),NaN,NaN,NaN,5.9,Ácido,Sí

In [1]:
import os

os.listdir()

['.ipynb_checkpoints',
 '0_ejemplo_clase_condicionales.ipynb',
 'resultado_oxigeno.csv',
 'resultado_ph.csv',
 'resultado_temperatura.csv',
 'reto1_temperatura.ipynb',
 'reto2_ph.ipynb',
 'reto3_oxigeno.ipynb',
 'reto4_integracion.ipynb']

In [2]:
import pandas as pd

temp = pd.read_csv("resultado_temperatura.csv")
ph = pd.read_csv("resultado_ph.csv")
ox = pd.read_csv("resultado_oxigeno.csv")

In [3]:
temp.head()

                          sitio  temperatura categoria_temp riesgo_termico
0                Río Subachoque         18.5           Baja             No
1   Quebrada Honda (Facatativá)         19.4           Baja             No
2          Río Botello (Madrid)         22.7          Media             No
3  Afluente San José (El Rosal)         20.1          Media             No
4                   Río Villeta         28.3           Alta             Sí

In [4]:
ph.head()

                          sitio   pH clasificacion_pH alerta_quimica
0                Río Subachoque  7.2         Adecuado             No
1   Quebrada Honda (Facatativá)  6.3            Ácido             Sí
2          Río Botello (Madrid)  6.8         Adecuado             No
3  Afluente San José (El Rosal)  7.9         Adecuado             No
4                   Río Villeta  8.7         Alcalino             Sí

In [5]:
ox.head()

,sitio,oxigeno,clasificacion_oxigeno,estres_biologico
0,Río Subachoque,7.8,Bueno,No
1,Quebrada Honda (Facatativá),6.2,Medio,No
2,Río Botello (Madrid),5.9,Medio,No
3,Afluente San José (El Rosal),8.3,Bueno,No
4,Río Villeta,6.1,Medio,No

In [6]:
df_final = pd.concat([temp, ph, ox], ignore_index=True)

df_final

,sitio,temperatura,categoria_temp,riesgo_termico,pH,clasificacion_pH,alerta_quimica,oxigeno,clasificacion_oxigeno,estres_biologico
0,Río Subachoque,18.5,Baja,No,NaN,NaN,NaN,NaN,NaN,NaN
1,Quebrada Honda (Facatativá),19.4,Baja,No,NaN,NaN,NaN,NaN,NaN,NaN
2,Río Botello (Madrid),22.7,Media,No,NaN,NaN,NaN,NaN,NaN,NaN
3,Afluente San José (El Rosal),20.1,Media,No,NaN,NaN,NaN,NaN,NaN,NaN
4,Río Villeta,28.3,Alta,Sí,NaN,NaN,NaN,NaN,NaN,NaN
5,Quebrada Cune (San Francisco),25.2,Media,No,NaN,NaN,NaN,NaN,NaN,NaN
6,Río Tobia (Nocaima),26.9,Alta,Sí,NaN,NaN,NaN,NaN,NaN,NaN
7,Quebrada Negra (La Vega),24.4,Media,No,NaN,NaN,NaN,NaN,NaN,NaN
8,Río Bahamón (Sasaima),27.6,Alta,Sí,NaN,NaN,NaN,NaN,NaN,NaN
9,Río Guayuriba (La Mesa),30.5,Alta,Sí,NaN,NaN,NaN,NaN,NaN,NaN
10,Río Subachoque,NaN,NaN,NaN,7.2,Adecuado,No,NaN,NaN,NaN
11,Quebrada Honda (Facatativá),NaN,NaN,NaN,6.3,Ácido,Sí,NaN,NaN,NaN
12,Río Botello (Madrid),NaN,NaN,NaN,6.8,Adecuado,No,NaN,NaN,NaN
13,Afluente San José (El Rosal),NaN,NaN,NaN,7.9,Adecuado,No,NaN,NaN,NaN
14,Río Villeta,NaN,NaN,NaN,8.7,Alcalino,Sí,NaN,NaN,NaN
15,Quebrada Cune (San Francisco),NaN,NaN,NaN,6.0,Ácido,Sí,NaN,NaN,NaN
16,Río Tobia (Nocaima),NaN,NaN,NaN,7.4,Adecuado,No,NaN,NaN,NaN
17,Quebrada Negra (La Vega),NaN,NaN,NaN,7.6,Adecuado,No,NaN,NaN,NaN
18,Río Bahamón (Sasaima),NaN,NaN,NaN,8.1,Adecuado,No,NaN,NaN,NaN
19,Río Guayuriba (La Mesa),NaN,NaN,NaN,5.9,Ácido,Sí,NaN,NaN,NaN
20,Río Subachoque,NaN,NaN,NaN,NaN,NaN,NaN,7.8,Bueno,No
21,Quebrada Honda (Facatativá),NaN,NaN,NaN,NaN,NaN,NaN,6.2,Medio,No
22,Río Botello (Madrid),NaN,NaN,NaN,NaN,NaN,NaN,5.9,Medio,No
23,Afluente San José (El Rosal),NaN,NaN,NaN,NaN,NaN,NaN,8.3,Bueno,No
24,Río Villeta,NaN,NaN,NaN,NaN,NaN,NaN,6.1,Medio,No
25,Quebrada Cune (San Francisco),NaN,NaN,NaN,NaN,NaN,NaN,4.5,Bajo,Sí
26,Río Tobia (Nocaima),NaN,NaN,NaN,NaN,NaN,NaN,5.2,Medio,No
27,Quebrada Negra (La Vega),NaN,NaN,NaN,NaN,NaN,NaN,7.0,Bueno,No
28,Río Bahamón (Sasaima),NaN,NaN,NaN,NaN,NaN,NaN,6.7,Medio,No
29,Río Guayuriba (La Mesa),NaN,NaN,NaN,NaN,NaN,NaN,4.8,Bajo,Sí

In [7]:
df_final.to_csv("resultado_integrado.csv", index=False)

print("Archivo integrado creado correctamente")

Archivo integrado creado correctamente

# Reto 4 - Integración

Se integraron los resultados de temperatura, pH y oxígeno disuelto utilizando pandas para generar un análisis conjunto de calidad del agua.